<a href="https://colab.research.google.com/github/file00/PyTorch/blob/main/Automatic_Differentiation_with_torch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Automatic Differentiation with torch.autograd

*   Detailed Theoretical Explanation: https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html#

In [17]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

### Tensors, Functions and Computational graph

In [18]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x79e5e7803f70>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x79e6d013a650>


### Computing Gradients

In [19]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3121, 0.0100, 0.0908],
        [0.3121, 0.0100, 0.0908],
        [0.3121, 0.0100, 0.0908],
        [0.3121, 0.0100, 0.0908],
        [0.3121, 0.0100, 0.0908]])
tensor([0.3121, 0.0100, 0.0908])


### Disabling Gradient Tracking

In [20]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


#### Another way to achieve the same result is to use the detach() method on the tensor:

In [21]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


### More on Computational Graphs

### Optional Reading: Tensor Gradients and Jacobian Products

In [22]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
